version: '3.5'

services:

  cassandra1:
    image: cassandra:latest
    container_name: cassandra1
    networks:
      cassandra-net:
        ipv4_address: 192.168.1.200
             
    ports:
      - "9042:9042"
    volumes:
      - /var/lib/cassandra/data_1:/var/lib/cassandra/data
    environment:
      - CASSANDRA_CLUSTER_NAME=MyCluster
      - CASSANDRA_SEEDS=192.168.1.200,192.168.1.201,192.168.1.202
      - CASSANDRA_LISTEN_ADDRESS=192.168.1.200
      - CASSANDRA_BROADCAST_ADDRESS=192.168.1.200

  cassandra2:
    image: cassandra:latest  
    container_name: cassandra2
    networks:
      cassandra-net:
        ipv4_address: 192.168.1.201
        
    ports:
      - "9043:9042"
    volumes:
      - /var/lib/cassandra/data_2:/var/lib/cassandra/data    
    environment:
      - CASSANDRA_CLUSTER_NAME=MyCluster
      - CASSANDRA_SEEDS=192.168.1.200,192.168.1.201,192.168.1.202
      - CASSANDRA_LISTEN_ADDRESS=192.168.1.201
      - CASSANDRA_BROADCAST_ADDRESS=192.168.1.201

  cassandra3:
    image: cassandra:latest
    container_name: cassandra3 
    networks:
      cassandra-net:
        ipv4_address: 192.168.1.202
        
    ports:
      - "9044:9042"
    volumes:
      - /var/lib/cassandra/data_3:/var/lib/cassandra/data
    environment:
      - CASSANDRA_CLUSTER_NAME=MyCluster
      - CASSANDRA_SEEDS=192.168.1.200,192.168.1.201,192.168.1.202
      - CASSANDRA_LISTEN_ADDRESS=192.168.1.202
      - CASSANDRA_BROADCAST_ADDRESS=192.168.1.202
        
networks:
    cassandra-net:
      driver: bridge
      driver_opts:
        parent: ens33
      ipam:
        config:
          - subnet: 192.168.1.0/24
            gateway: 192.168.1.1
